language: node_js
node_js:
  - 4.4.6

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    # - BROWSER=chrome  BVER=beta
    # - BROWSER=chrome  BVER=unstable
    # - BROWSER=firefox BVER=stable
    # - BROWSER=firefox BVER=beta
    # - BROWSER=firefox BVER=nightly

matrix:
  fast_finish: true

  # allowed_failures:
  #   - env: BROWSER=chrome  BVER=unstable
  #   - env: BROWSER=firefox BVER=nightly

# before_install:
#   - ./setup.sh

install:
  - npm install
  - ./node_modules/.bin/webdriver-manager update

before_script:
  # Setup dummy display
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  # Start the socket server for testing.
  - npm start &
  - sleep 5

script:
  # - grunt travis-protractor
  - npm test
